# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.3
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 142847732+trendSetters01@users.noreply.github.com
author_name: trendSetters01
cloud_provider: none
preset_name: production
project_name: Dao

